import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'Terms of Service - OnlyBae' };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <Link href="/browse" className="text-muted hover:text-foreground text-sm transition-colors mb-8 inline-block">&larr; Back</Link>

        <h1 className="text-3xl font-bold text-foreground mb-2">Terms of Service</h1>
        <p className="text-muted text-sm mb-8">Last updated: March 27, 2026</p>

        <div className="prose-custom">
          <p>Welcome to OnlyBae.vip!</p>
          <p>These Terms of Service (&quot;Terms&quot;) govern your access to and use of the website available at www.OnlyBae.vip (the &quot;Website&quot;) and the services available through the Website (the &quot;Services&quot;), which are owned and operated by BAE Media LLC, a Delaware limited liability company (&quot;BAE Media&quot;, &quot;We&quot;, &quot;Us&quot;, or &quot;Our&quot;).</p>
          <p>The Services constitute an AI-powered dating and companion platform featuring exclusively fictional, AI-generated characters. All characters, images, videos, galleries, and video clips are pre-created and provided by the platform. Users may chat with these existing AI characters and optionally connect compatible adult toys that sync to pre-compiled short AI-generated video clips. The toy will respond in real time to the selected video while synced. All content on the platform is 100% fictional and generated by artificial intelligence. No real human beings, models, actors, or individuals are depicted or involved in any content.</p>
          <p>Before accessing or using the Website or Services, you (&quot;You&quot; or &quot;User&quot;) must carefully review and agree to these Terms. If you do not agree, you must not access or use the Website or Services.</p>

          <h2>1. About OnlyBae.vip</h2>
          <p>The Services allow users to interact with pre-existing fictional AI-generated characters for companionship and dating purposes. All content (characters, images, galleries, and videos) is pre-created using generative artificial intelligence and is provided for adult entertainment. Users cannot generate new characters, images, videos, or other content. The adult toy sync feature allows compatible toys to respond to pre-compiled AI video clips. Use of the adult toy sync feature is at your own risk; you must ensure compatibility with your device and follow all manufacturer safety instructions. BAE Media is not liable for any injury, damage, or malfunction arising from toy use.</p>

          <h2>2. Your Acceptance of These Terms</h2>
          <p>By using the Website or Services, you represent and warrant that: (i) you are at least 18 years old (or the age of majority in your jurisdiction, whichever is greater) and have the full legal capacity to enter into these Terms; (ii) you will comply with all provisions of these Terms in good faith; and (iii) you have not been previously suspended or removed from the Services.</p>
          <p>You must also agree to our <Link href="/privacy" className="text-accent hover:underline">Privacy Policy</Link>, <Link href="/content-removal" className="text-accent hover:underline">Content Removal Policy</Link>, and <Link href="/underage-policy" className="text-accent hover:underline">Underage Policy</Link>. If you are under 18 or do not agree to any policy, do not use the Website or Services.</p>

          <h2>3. Modifications</h2>
          <p>We may modify, suspend, or discontinue the Website or Services (or any part thereof) at any time with or without notice. We may also update these Terms. Continued use after changes constitutes acceptance of the revised Terms. Significant changes will be notified via the Website or email (if provided).</p>

          <h2>4. Relationship to Other Policies</h2>
          <p>These Terms work together with our Privacy Policy, Content Removal Policy (which includes our Blocked Content and Complaint procedures), and Underage Policy. All are binding.</p>

          <h2>5. Links</h2>
          <p>The Services may contain links to third-party sites. We are not responsible for their content or practices. Linking to our Website is permitted only under the conditions set forth in the reference policies (plain text link, no framing, no implication of endorsement, etc.). We may revoke linking permission at any time.</p>

          <h2>6. User Content and Platform Content</h2>
          <p>All characters, images, galleries, videos, and clips available on the Services are owned or licensed by BAE Media and are provided as-is for your personal, non-commercial use. You may not copy, reproduce, distribute, modify, or create derivative works from any platform content. You are responsible for your chat messages and interactions with the AI characters. We do not allow users to generate new visual or video content through prompts or any other means.</p>

          <h2>7. 18 U.S.C. &sect; 2257 Exemption Statement</h2>
          <p>All visual depictions displayed on this Website and in the Services are exempt from the provisions of 18 U.S.C. &sect;2257, 2257A, and/or 28 C.F.R. 75 because:</p>
          <ul>
            <li>They do not portray actual human beings engaged in actual sexually explicit conduct.</li>
            <li>They are exclusively artificial creations generated by Artificial Intelligence (AI).</li>
            <li>No human models, actors, actresses, or other persons appear in any of the generated images, videos, or other content on this Website or in the Services.</li>
          </ul>
          <p>BAE Media is committed to displaying only AI-generated content that complies with all applicable laws.</p>

          <h2>8. Prohibited Conduct</h2>
          <p>You agree not to use the Services for any unlawful purpose, to attempt to generate new content (which is not permitted), or to violate any of our policies. Violations may result in account suspension or termination.</p>

          <h2>9. Disclaimers and Limitation of Liability</h2>
          <p>The Website and Services are provided &quot;as is.&quot; We disclaim all warranties. We are not liable for any indirect, incidental, or consequential damages, including any issues arising from AI-generated content, adult toy use, or third-party devices. Our total liability shall not exceed amounts you paid to us in the preceding 12 months (or $100 if no payment).</p>

          <h2>10. Indemnification</h2>
          <p>You agree to indemnify and hold BAE Media harmless from any claims arising from your use of the Services, your chat interactions, or your adult toy synchronization.</p>

          <h2>11. Governing Law</h2>
          <p>These Terms are governed by the laws of the State of Delaware, USA, without regard to conflict of laws principles. Disputes shall be resolved exclusively in the courts of Delaware.</p>

          <h2>12. Termination</h2>
          <p>We may terminate or suspend your access at any time for any reason. Upon termination, your right to use the Services ceases immediately.</p>

          <h2>13. Contact</h2>
          <p>For questions about these Terms, contact us at <a href="mailto:support@onlybae.vip" className="text-accent hover:underline">support@onlybae.vip</a></p>

          <p className="mt-8 text-muted">By using the Website or Services, you acknowledge that you have read, understood, and agree to be bound by these Terms.</p>
        </div>
      </div>
    </div>
  );
}
